[package]
name = "jasmin-rest"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["process", "sync", "rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }

